-- SQLite

WITH TABLE1 AS (
select RACE,
COUNT() AS COUNT_OF
from offender
GROUP BY RACE
ORDER BY COUNT_OF DESC
),

TABLE2 AS (
SELECT SUM(TABLE1.COUNT_OF) AS ALL_EXECUTIONS
FROM TABLE1)


SELECT TABLE1.RACE,TABLE1.COUNT_OF,
ROUND((TABLE1.COUNT_OF * 1.0 / TABLE2.ALL_EXECUTIONS) * 100, 2 ) AS PERCENTAGE_OF_TOTAL
FROM TABLE1, TABLE2
